---
- name: Splunk Infrastructure Build
  hosts: all

  tasks:
    - ansible.builtin.import_role:
        name: clustermanager

    - name: indexer cluster configuration
      ansible.builtin.import_role:
        name: indexers

    - name: searchheads indexer cluster configuration
      ansible.builtin.import_role:
        name: searchheads

    - name: deployer  cluster configuration
      ansible.builtin.import_role:
        name: deployer
