- name: Copy searchhead02 configuration to etc/apps
  ansible.builtin.copy:
    src: /home/ansible/ansible-splunk-playbooks/seachheads_clustering/TA_searchhead-sh02_cluster
    dest: /opt/splunk/etc/apps
    owner: splunk_user
    group: splunk_user
    mode: "0644"
  when: inventory_hostname == groups['searchheads'][1]

- name: Splunk Restart
  shell: sudo systemctl restart Splunkd
  #ansible.builtin.systemd:
  #      state: restarted
  #     name: Splunkd
  when: inventory_hostname == groups['searchheads'][1]

- name: searchhead02 captain
  shell: /opt/splunk/bin/splunk bootstrap shcluster-captain -servers_list "https://searchhead01.eni.nilipay.com:8089,https://searchhead02.eni.nilipay.com:8089" -auth admin:P@ssword123
  when: inventory_hostname == groups['searchheads'][1]

